import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Welcome from '../components/Welcome'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import { useRef, useState, useEffect, useLayoutEffect } from 'react'


export default function Home() {

  const [one, setOne] = useState<string>('base one')
  const [two, setTwo] = useState<string>('base two')
  const [three, setThree] = useState<string>('base three')
  const [bg, setBg] = useState<string>('background bg')



  const aboutRef: any = useRef()
  const skillsRef: any = useRef()
  const projectsRef: any = useRef()
  const contactRef: any = useRef()
  const footerRef: any = useRef()
  
  
  // useEffect (() => {
  //   setAboutHeight(aboutRef.current.getBoundingClientRect().top)

  //   // if (window.scrollY > aboutHeight && aboutHeight > 0) {
  //   //   setOne('base aboutOne')
  //   //   setTwo('base aboutTwo')
  //   //   setThree('base aboutThree')
  //   // } else {
  //   //   setOne('base one')
  //   //   setTwo('base two')
  //   //   setThree('base three')
  //   // }
  // }, [])



  // console.log(window.scrollY)
  // console.log(contactHeight)
  // console.log(footerHeight)

  useLayoutEffect(() => {
    // console.log('about: ', aboutRef.current.getBoundingClientRect().top)
    // console.log('skills: ', skillsRef.current.getBoundingClientRect().top)
    // console.log('projects: ', projectsRef.current.getBoundingClientRect().top)
    // console.log('contact: ', contactRef.current.getBoundingClientRect().top)
    window.addEventListener('scroll', onScroll)
    return () => {
      window.removeEventListener('scroll', onScroll)
    }
  },[])

  function aboutTheme(): void {
    setOne('base aboutOne')
    setTwo('base aboutTwo')
    setThree('base aboutThree')
    setBg('background aboutBg')
  }

  function skillsTheme(): void {
    setOne('base skillsOne')
    setTwo('base skillsTwo')
    setThree('base skillsThree')
    setBg('background skillsBg')
  }

  function projectsTheme(): void {
    setOne('base projectsOne')
    setTwo('base projectsTwo')
    setThree('base projectsThree')
    setBg('background projectsBg')
  }

  function contactTheme(): void {
    setOne('base contactOne')
    setTwo('base contactTwo')
    setThree('base contactThree')
    setBg('background contactBg')
  }

  const onScroll = () => {
    // console.log('scrollPos: ', scrollPos)
    // console.log('current scroll position: ', scrollPos)
    // console.log('about height: ', aboutHeight)
    // console.log('about height: ',aboutRef.current.getBoundingClientRect().top)
    // console.log('client height', aboutRef.current.clientHeight)
    // console.log('clientRect', aboutRef.current.getBoundingClientRect().top)
    console.log('scroll position: ',window.scrollY)
    console.log('height: ', skillsRef.current.clientHeight)
    if (window.scrollY > aboutRef.current.getBoundingClientRect().top && window.scrollY < aboutRef.current.offsetTop + aboutRef.current.clientHeight / 3) {
      aboutTheme()
    } else if (window.scrollY > skillsRef.current.getBoundingClientRect().top && window.scrollY < skillsRef.current.offsetTop + skillsRef.current.clientHeight / 3) {
      skillsTheme()
    } else if (window.scrollY > projectsRef.current.getBoundingClientRect().top && window.scrollY < projectsRef.current.offsetTop + projectsRef.current.clientHeight / 3) {
      projectsTheme()
    } else {
      setOne('base one')
      setTwo('base two')
      setThree('base three')
      setBg('background bg')
    }
  }


  const aboutClick = (): void => {
    //.current is verification that your element has rendered
    if(aboutRef.current){
        aboutRef.current.scrollIntoView({ 
           behavior: "smooth",
           block: "center"
      })
    }
  }

  const skillsClick = (): void => {
    if(skillsRef.current){
      skillsRef.current.scrollIntoView({ 
         behavior: "smooth",
         block: "center"
      })
    }
  }

  const projectsClick = (): void => {
    if(projectsRef.current){
      projectsRef.current.scrollIntoView({ 
         behavior: "smooth",
         block: "center"
      })
    }
  }

  const contactClick = (): void => { 
    if(contactRef.current){
      contactRef.current.scrollIntoView({ 
         behavior: "smooth",
         block: "center"
      })
    }
  }

  // function handleScroll (y: number, one: string, two: string, three: string): void {
  //   if y > 100vh
  // }
  

  return (
    <div className="indexComponent">
      <Head>
        <title>Reinard Pagdilao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <button onClick={aboutClick} className="navButton">About</button>
        <button onClick={skillsClick} className="navButton">Skills</button>
        <button onClick={projectsClick} className="navButton">Projects</button>
        <button onClick={contactClick} className="navButton">Contact</button>
      </nav>
      <div className={bg}>
        <div id="one" className={one}></div>
        <div id="two" className={two}></div>
        <div id="three" className={three}></div>
      </div>

      <div className='index'>
        <div className="welcome">
          <Welcome />
        </div>
        <div ref={aboutRef} className="about">
          <About /> 
        </div>
        <div ref={skillsRef} className="skills">
          <Skills />
        </div>
        <div ref={projectsRef} className="projects">
          <Projects />
        </div>
        <div ref={contactRef} className="contact">
          <Contact />
        </div>
        <div ref={footerRef} className="footer">
          <Footer />
        </div>
      </div>
      <style jsx>{`
        nav {
            display: flex;
            position: fixed;
            width: 100%;
            background: #071b3a66;
            height: 30px;
        }
        
        .navButton {
            margin-top: 3px;
            margin-bottom: 3px;
            margin-left: 5px;
            border-radius: 20px;
            border: none;
            font-size: .2 rem;
            // color: #36eca7;
        }


        @keyframes fly {
          100% {
            transform:rotate(1turn) translate(100px) rotate(-1turn);
          }
        }
        
        @keyframes flyPlus {
          100% {
            transform:rotate(-1turn) translate(100px) rotate(1turn);
          }
        }

        .background {
          width: 100%;
          height: 100%;
          position: fixed;
          z-index: -1;
          transition-duration: 1s;
        }

        .bg {
          background: #071b3a;
        }

        .aboutBg {
          background: #3E5D58;
        }

        .skillsBg {
          background: #ffaf7a;
        }

        .projectsBg {
          background: #DF5E5E;
        }

        .contactBg {
          background: #3E5D58;
        }

        .base {
          position: absolute;
          filter: blur(60px);
          opacity: .8;
        }

        .one {
          border-radius: 100%;
          width: 600px;
          height: 600px;
          background-color: #373372;
          top:-200px;
          left: 150px;
          z-index: 3;
          animation: fly 10s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .aboutOne {
          border-radius: 100%;
          width: 600px;
          height: 600px;
          background-color: #92ACA0;
          top:-200px;
          left: 150px;
          z-index: 3;
          animation: fly 10s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .skillsOne {
          border-radius: 100%;
          width: 600px;
          height: 600px;
          background-color: #ff9d5c;
          top:-200px;
          left: 150px;
          z-index: 3;
          animation: fly 10s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .projectsOne {
          border-radius: 100%;
          width: 600px;
          height: 600px;
          background-color: #E98580;
          top:-200px;
          left: 150px;
          z-index: 3;
          animation: fly 10s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .contactOne {
          border-radius: 100%;
          width: 600px;
          height: 600px;
          background-color: #92ACA0;
          top:-200px;
          left: 150px;
          z-index: 3;
          animation: fly 10s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }
        
        .two {
          width: 500px;
          height: 800px;
          background-color: #7C336C;
          bottom:-30px;
          left:-80px;
          transition-duration: 1s;
          transform:rotate(0) translate(80px) rotate(0);
        }

        .aboutTwo {
          width: 500px;
          height: 800px;
          background-color: #55827b;
          bottom:-30px;
          left:-80px;
          transition-duration: 1s;
          transform:rotate(0) translate(80px) rotate(0);
        }

        .skillsTwo {
          width: 500px;
          height: 800px;
          background-color: #fc8451;
          bottom:-30px;
          left:-80px;
          transition-duration: 1s;
          transform:rotate(0) translate(80px) rotate(0);
        }

        .projectsTwo {
          width: 500px;
          height: 800px;
          background-color: #FDD2BF;
          bottom:-30px;
          left:-80px;
          transition-duration: 1s;
          transform:rotate(0) translate(80px) rotate(0);
        }

        .contactTwo {
          width: 500px;
          height: 800px;
          background-color: #55827b;
          bottom:-30px;
          left:-80px;
          transition-duration: 1s;
          transform:rotate(0) translate(80px) rotate(0);
        }
        
        .three {
          border-radius: 100%;
          width: 500px;
          height: 500px;
          bottom:10px;
          right:-50px;
          opacity: .4;
          background-color: #B3588A;
          animation: flyPlus 18s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .aboutThree {
          border-radius: 100%;
          width: 500px;
          height: 500px;
          bottom:10px;
          right:-50px;
          opacity: .5;
          background-color: #DDE5ED;
          animation: flyPlus 18s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .skillsThree {
          border-radius: 100%;
          width: 500px;
          height: 500px;
          bottom:10px;
          right:-50px;
          opacity: .5;
          background-color: #ff5349;
          animation: flyPlus 18s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .projectsThree {
          border-radius: 100%;
          width: 500px;
          height: 500px;
          bottom:10px;
          right:-50px;
          opacity: .5;
          background-color: #492F10;
          animation: flyPlus 18s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .contactThree {
          border-radius: 100%;
          width: 500px;
          height: 500px;
          bottom:10px;
          right:-50px;
          opacity: .5;
          background-color: #DDE5ED;
          animation: flyPlus 18s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
          transition-duration: 1s;
        }

        .index {
          padding: 0 0.5rem;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          color: #ffffff;
        }

        .welcome {
          display: flex;
          align-items: center;
          min-height: 100vh;
          height: 100vh;
        }

        .about {
          display: flex;
          min-height: 100vh;
          height: 100vh;
          align-items: center;
        }

        .skills {
          display: flex;
          min-height: 100vh;
          height: 100vh;
          align-items: center;
        }

        .projects {
          display: flex;
          min-height: 100vh;
          height: 100vh;
          align-items: center;
        }

        .contact {
          display: flex;
          min-height: 100vh;
          height: 100vh;
          align-items: center;
        }



      `}</style>
    </div>
  )
}
