import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Welcome from '../components/Welcome'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import { useRef, useState } from 'react'


export default function Home() {

  const [one, setOne] = useState('base one')
  const [two, setTwo] = useState('base two')
  const [three, setThree] = useState('base three')

  const isBrowser: boolean = typeof window! == 'undefined'
  const scrollRef: any = useRef(0)
  const aboutRef: any = useRef()
  const skillsRef: any = useRef()
  const projectsRef: any = useRef()
  const contactRef: any = useRef()
  let y: number
  if (!isBrowser) {
    y = window.pageYOffset
    scrollRef.current.y
  }

  const aboutClick = (event: any): void => {
    //.current is verification that your element has rendered
    if(aboutRef.current){
        aboutRef.current.scrollIntoView({ 
           behavior: "smooth"
      })
    }
  }

  const skillsClick = (event: any): void => {
    if(skillsRef.current){
      skillsRef.current.scrollIntoView({ 
         behavior: "smooth"
      })
    }
  }

  const projectsClick = (event: any): void => {
    if(projectsRef.current){
      projectsRef.current.scrollIntoView({ 
         behavior: "smooth"
      })
    }
  }

  const contactClick = (event: any): void => { 
    if(contactRef.current){
      contactRef.current.scrollIntoView({ 
         behavior: "smooth"
      })
    }
  }

  // function handleScroll (y: number, one: string, two: string, three: string): void {
  //   if y > 100vh
  // }
  

  return (
    <div className="indexComponent">
      <Head>
        <title>Reinard Pagdilao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <button onClick={aboutClick} className="navButton">About</button>
        <button onClick={skillsClick} className="navButton">Skills</button>
        <button onClick={projectsClick} className="navButton">Projects</button>
        <button onClick={contactClick} className="navButton">Contact</button>
      </nav>
      <div className="background">
        <div id="one" className={one}></div>
        <div id="two" className={two}></div>
        <div id="three" className={three}></div>
      </div>

      <div className='index'>
        <div className="welcome">
          <Welcome />
        </div>
        <div ref={aboutRef} className="about">
          <About /> 
        </div>
        <div ref={skillsRef} className="skills">
          <Skills />
        </div>
        <div ref={projectsRef} className="projects">
          <Projects />
        </div>
        <div ref={contactRef} className="contact">
          <Contact />
        </div>
        <div className="footer">
          <Footer />
        </div>
      </div>
      <style jsx>{`
        nav {
            display: flex;
            position: fixed;
            width: 100%;
            background: #071b3a66;
            height: 30px;
        }
        
        .navButton {
            margin-top: 3px;
            margin-bottom: 3px;
            margin-left: 5px;
            border-radius: 20px;
            border: none;
            font-size: .2 rem;
            // color: #36eca7;
        }


        @keyframes fly {
          100% {
            transform:rotate(1turn) translate(100px) rotate(-1turn);
          }
        }
        
        @keyframes flyPlus {
          100% {
            transform:rotate(-1turn) translate(100px) rotate(1turn);
          }
        }

        .background {
          width: 100%;
          height: 100%;
          position: fixed;
          background: #071b3a;
          z-index: -1;
        }

        .base {
          position: absolute;
          filter: blur(60px);
          opacity: .8;
        }

        .one {
          border-radius: 100%;
          width: 600px;
          height: 600px;
          background-color: #373372;
          top:-200px;
          left: 150px;
          z-index: 3;
          animation: fly 10s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
        }

        .aboutOne {
          border-radius: 100%;
          width: 600px;
          height: 600px;
          background-color: #DDE5ED;
          top:-200px;
          left: 150px;
          z-index: 3;
          animation: fly 10s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
        }
        
        .two {
          width: 500px;
          height: 800px;
          background-color: #7C336C;
          bottom:-30px;
          left:-80px;
        }

        .aboutTwo {
          width: 500px;
          height: 800px;
          background-color: #92ACA0;
          bottom:-30px;
          left:-80px;
        }
        
        .three {
          border-radius: 100%;
          width: 500px;
          height: 500px;
          bottom:10px;
          right:-50px;
          opacity: .6;
          background-color: #B3588A;
          animation: flyPlus 18s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
        }

        .aboutThree {
          border-radius: 100%;
          width: 500px;
          height: 500px;
          bottom:10px;
          right:-50px;
          opacity: .6;
          background-color: #3E5D58;
          animation: flyPlus 18s linear infinite;
          transform:rotate(0) translate(80px) rotate(0);
        }

        .index {
          padding: 0 0.5rem;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          color: #ffffff;
        }

        .welcome {
          display: flex;
          align-items: center;
          min-height: 100vh;
          height: 100vh;
        }

        .about {
          display: flex;
          min-height: 75vh;
          height: 75vh;
          align-items: center;
        }

        .skills {
          display: flex;
          min-height: 50vh;
          height: 50vh;
          align-items: center;
        }

        .projects {
          display: flex;
          min-height: 75vh;
          height: 75vh;
          align-items: center;
        }

        .contact {
          display: flex;
          min-height: 75vh;
          height: 75vh;
          align-items: center;
        }



      `}</style>
    </div>
  )
}
